import {
  Award,
  Star,
  Clock,
  Zap,
  Shield,
  Users,
  Search,
  FileText,
  Target,
  Globe,
  BarChart3,
  TrendingUp,
  Fingerprint,
  Layers,
  Heart,
  BadgeCheck,
  BarChart,
  Database,
  Share2,
  Mail,
  Cog,
  MousePointerClick,
  CheckCircle,
  ChevronDown,
  ArrowRight,
  Phone,
  HeartPulse,
  Scale,
  Utensils,
  Building,
  ShoppingCart,
  Wrench,
  Dumbbell,
  Bed,
  Landmark,
  GraduationCap,
  Car,
  Shirt,
  Sparkles,
  Cpu,
  Ruler,
  Calculator,
  Smile,
  Activity,
  MessageCircle,
  Camera,
  type LucideIcon as LucideIconType,
} from 'lucide-react'

const iconMap: Record<string, LucideIconType> = {
  award: Award,
  star: Star,
  clock: Clock,
  zap: Zap,
  shield: Shield,
  users: Users,
  search: Search,
  'file-text': FileText,
  target: Target,
  globe: Globe,
  'bar-chart-3': BarChart3,
  'bar-chart': BarChart,
  'trending-up': TrendingUp,
  fingerprint: Fingerprint,
  layers: Layers,
  heart: Heart,
  'badge-check': BadgeCheck,
  database: Database,
  'share-2': Share2,
  mail: Mail,
  cog: Cog,
  'mouse-pointer-click': MousePointerClick,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'arrow-right': ArrowRight,
  phone: Phone,
  'heart-pulse': HeartPulse,
  scale: Scale,
  utensils: Utensils,
  building: Building,
  'shopping-cart': ShoppingCart,
  wrench: Wrench,
  dumbbell: Dumbbell,
  bed: Bed,
  landmark: Landmark,
  'graduation-cap': GraduationCap,
  car: Car,
  shirt: Shirt,
  sparkles: Sparkles,
  cpu: Cpu,
  ruler: Ruler,
  calculator: Calculator,
  smile: Smile,
  activity: Activity,
  'message-circle': MessageCircle,
  camera: Camera,
}

export function LucideIcon({ name, className }: { name: string; className?: string }) {
  const Icon = iconMap[name]
  if (!Icon) return null
  return <Icon className={className} />
}

export { CheckCircle, ChevronDown, ArrowRight, Phone }
