import type { Locale, LandingPageLabels, LocalBusinessInfo } from './types'

export const sharedLabels: Record<Locale, LandingPageLabels> = {
  de: {
    pricingTitle: 'Unsere Pakete',
    pricingDescription: 'Transparente Preise für jeden Bedarf.',
    processTitle: 'Unser Prozess',
    processSubtitle: 'So arbeiten wir gemeinsam an Ihrem Erfolg.',
    technologiesTitle: 'Technologien',
    technologiesDescription: 'Wir setzen auf bewährte und moderne Technologien für beste Ergebnisse.',
    servicesTitle: 'Unsere Leistungen',
    servicesDescription: 'Umfassende Lösungen für Ihren Erfolg.',
    resultsTitle: 'Ergebnisse',
    faqTitle: 'Häufige Fragen',
    faqSubtitle: 'Antworten auf häufig gestellte Fragen.',
    relatedServicesTitle: 'Verwandte Leistungen',
    ctaTitle: 'Bereit für Ihr Projekt?',
    ctaDescription: 'Lassen Sie uns über Ihr Projekt sprechen. Kostenloses Erstgespräch ohne Verpflichtung.',
    ctaButton: 'Projekt anfragen',
    popular: 'Beliebt',
    oneTime: 'einmalig',
    sendRequest: 'Anfrage senden',
    learnMore: 'Mehr erfahren',
  },
  en: {
    pricingTitle: 'Our Packages',
    pricingDescription: 'Transparent pricing for every need.',
    processTitle: 'Our Process',
    processSubtitle: 'How we work together for your success.',
    technologiesTitle: 'Technologies',
    technologiesDescription: 'We rely on proven and modern technologies for best results.',
    servicesTitle: 'Our Services',
    servicesDescription: 'Comprehensive solutions for your success.',
    resultsTitle: 'Results',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Answers to frequently asked questions.',
    relatedServicesTitle: 'Related Services',
    ctaTitle: 'Ready for Your Project?',
    ctaDescription: "Let's talk about your project. Free initial consultation with no obligation.",
    ctaButton: 'Request Project',
    popular: 'Popular',
    oneTime: 'one-time',
    sendRequest: 'Send Request',
    learnMore: 'Learn More',
  },
  ru: {
    pricingTitle: 'Наши пакеты',
    pricingDescription: 'Прозрачные цены для любых задач.',
    processTitle: 'Наш процесс',
    processSubtitle: 'Как мы работаем вместе над вашим успехом.',
    technologiesTitle: 'Технологии',
    technologiesDescription: 'Мы используем проверенные и современные технологии для лучших результатов.',
    servicesTitle: 'Наши услуги',
    servicesDescription: 'Комплексные решения для вашего успеха.',
    resultsTitle: 'Результаты',
    faqTitle: 'Часто задаваемые вопросы',
    faqSubtitle: 'Ответы на часто задаваемые вопросы.',
    relatedServicesTitle: 'Связанные услуги',
    ctaTitle: 'Готовы к вашему проекту?',
    ctaDescription: 'Давайте обсудим ваш проект. Бесплатная первичная консультация без обязательств.',
    ctaButton: 'Заказать проект',
    popular: 'Популярный',
    oneTime: 'единоразово',
    sendRequest: 'Отправить запрос',
    learnMore: 'Узнать больше',
  },
}

export const localBusinessVienna: LocalBusinessInfo = {
  name: 'GoldenWing Creative Studios',
  address: 'Czeikestrasse 4/21, 1100 Wien',
  city: 'Wien',
  country: 'AT',
  email: 'office@goldenwing.at',
}

export const localBusinessDubai: LocalBusinessInfo = {
  name: 'GoldenWing Creative Studios',
  address: 'DAMAC Executive Bay Tower B, Office 1406, Business Bay',
  city: 'Dubai',
  country: 'AE',
  email: 'office@goldenwing.at',
}
